# Generated by Django 5.0.4 on 2024-05-06 06:34

import django.apps
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def insert_documents_types_initial_data(apps: django.apps.apps, schema_editor):
    document_type_model = apps.get_model("api", "DocumentType")
    document_type_model.objects.create(name="CPF")
    document_type_model.objects.create(name="CNPJ")


def insert_farm_culture_types_initial_data(apps: django.apps.apps, schema_editor):
    culture_type_model = apps.get_model("api", "FarmCultureType")
    culture_type_model.objects.create(name="Soja")
    culture_type_model.objects.create(name="Milho")
    culture_type_model.objects.create(name="Algodão")
    culture_type_model.objects.create(name="Café")
    culture_type_model.objects.create(name="Cana de Açucar")


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=10)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "document_type",
            },
        ),
        migrations.CreateModel(
            name="FarmCultureType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "farm_culture_type",
            },
        ),
        migrations.CreateModel(
            name="RuralProducer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("document_number", models.CharField(max_length=14)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=100)),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.documenttype",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rural_producer",
            },
        ),
        migrations.CreateModel(
            name="FarmRuralProducer",
            fields=[
                ("name", models.CharField(max_length=255)),
                (
                    "total_hectare_area",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "arable_hectare_area",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "vegetation_hectare_area",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "rural_producer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.ruralproducer",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "farm_rural_producer",
            },
        ),
        migrations.CreateModel(
            name="FarmCultureRuralProducer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "used_hectare_area",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "farm_culture_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.farmculturetype",
                    ),
                ),
                (
                    "farm_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.farmruralproducer",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "farm_culture_rural_producer",
                "unique_together": {("farm_id", "farm_culture_type")},
            },
        ),
        migrations.RunPython(insert_documents_types_initial_data),
        migrations.RunPython(insert_farm_culture_types_initial_data),
    ]
