# Generated by Django 5.0.4 on 2024-05-08 08:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def insert_farm_culture_types_initial_data(apps: django.apps.apps, schema_editor):
    culture_type_model = apps.get_model("api", "FarmCultureType")
    culture_type_model.objects.create(name="Soja")
    culture_type_model.objects.create(name="Milho")
    culture_type_model.objects.create(name="Algodão")
    culture_type_model.objects.create(name="Café")
    culture_type_model.objects.create(name="Cana de Açucar")

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FarmCultureType",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "farm_culture_type",
            },
        ),
        migrations.CreateModel(
            name="RuralProducer",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("document_number", models.CharField(max_length=14, unique=True)),
                (
                    "document_type",
                    models.CharField(choices=[("CPF", "Cpf"), ("CNPJ", "Cnpj")]),
                ),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "rural_producer",
            },
        ),
        migrations.CreateModel(
            name="FarmRuralProducer",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "total_hectare_area",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "arable_hectare_area",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "vegetation_hectare_area",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "rural_producer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm",
                        to="api.ruralproducer",
                    ),
                ),
            ],
            options={
                "db_table": "farm_rural_producer",
            },
        ),
        migrations.CreateModel(
            name="FarmCultureRuralProducer",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "farm_culture_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.farmculturetype",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cultures",
                        to="api.farmruralproducer",
                    ),
                ),
            ],
            options={
                "db_table": "farm_culture_rural_producer",
                "unique_together": {("farm_id", "farm_culture_type")},
            },
        ),
        migrations.RunPython(insert_farm_culture_types_initial_data)
    ]
