# Generated by Django 5.0.4 on 2024-05-08 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmcultureruralproducer",
            name="farm_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cultures",
                to="api.farmruralproducer",
            ),
        ),
        migrations.AlterField(
            model_name="farmruralproducer",
            name="rural_producer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farm",
                to="api.ruralproducer",
            ),
        ),
        migrations.AlterField(
            model_name="ruralproducer",
            name="document_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.documenttype"
            ),
        ),
    ]
