# Generated by Django 5.0.4 on 2024-05-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_farmcultureruralproducer_farm_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="farmcultureruralproducer",
            old_name="farm_id",
            new_name="farm",
        ),
    ]
