version: '3.9'
services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: rural
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${PWD}/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build: .
    command: 
      - /bin/bash
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    ports:
        - 8000:8000
    environment:
      - DB_NAME=rural
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_PORT=5432
      - ENV=development
      - API_SECRET=secreto1234
    env_file:
      - ./config/.env
    depends_on:
      - db